# Generated by Powerlevel10k configuration wizard on 2025-03-27.
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.

# Use modern terminal features
setopt prompt_subst

# Load instant prompt for speed
[[ ! -f ~/.p10k.zsh-instant-prompt ]] || source ~/.p10k.zsh-instant-prompt

# Load Powerlevel10k theme
source ~/.powerlevel10k/powerlevel10k.zsh-theme

# Prompt Appearance
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# Prompt Prefixes
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="❯ "

# Segment Separators
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=$''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=$''

# Prompt Elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir interface ip ip_public vpn_status vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs time)

# OS Icon
POWERLEVEL9K_OS_ICON_FOREGROUND=33
POWERLEVEL9K_OS_ICON_BACKGROUND=235

# Directory Segment
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_DIR_FOREGROUND=33
POWERLEVEL9K_DIR_BACKGROUND=235
POWERLEVEL9K_DIR_SHORTEN_STRATEGY="truncate_to_last"
POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=""

# Git Status
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=235
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=208
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=235
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=202
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=235
POWERLEVEL9K_VCS_LOADING_FOREGROUND=244
POWERLEVEL9K_VCS_LOADING_BACKGROUND=235

# Exit Status
POWERLEVEL9K_STATUS_OK_FOREGROUND=2
POWERLEVEL9K_STATUS_OK_BACKGROUND=0
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
POWERLEVEL9K_STATUS_ERROR_BACKGROUND=0

# Command Execution Time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=250
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=238
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0

# Background Jobs
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=33
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=0

# Time Segment
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
POWERLEVEL9K_TIME_FOREGROUND=66
POWERLEVEL9K_TIME_BACKGROUND=0

# Icons and Spacing
POWERLEVEL9K_ICON_PADDING=none
POWERLEVEL9K_ICON_BEFORE_CONTENT=true

# Enable transient prompt (hide old prompt when scrolling)
POWERLEVEL9K_TRANSIENT_PROMPT=always

# Suppress Powerlevel10k warning about early output
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# IP Address Segment (Private IP)
function prompt_ip() {
  local ip=$(ip route get 1 | awk '{print $NF; exit}')
  [[ -n $ip ]] && p10k segment -b 237 -f 255 -i '' -t "$ip"
}

# Public IP Segment
function prompt_ip_public() {
  local ip=$(curl -s https://api.ipify.org)
  [[ -n $ip ]] && p10k segment -b 238 -f 255 -i '' -t "$ip"
}

# Network Interface Segment
function prompt_interface() {
  local iface=$(ip route | awk '/default/ {print $5; exit}')
  [[ -n $iface ]] && p10k segment -b 238 -f 255 -i '' -t "$iface"
}

# VPN Status Segment
function prompt_vpn_status() {
  if ip a | grep -q 'tun0'; then
    p10k segment -b 28 -f 15 -i '' -t 'VPN'
  else
    p10k segment -b 52 -f 255 -i '' -t 'No VPN'
  fi
}

# Hacker-style greeting prompt
print -P "%F{green}
%F{blue} [ S E C U R E O P S -  D I G I T A L   F O R T I F I C A T I O N S ]%f"

# Fun startup message
print -P "%F{red}Initializing secure shell on %F{yellow}%m%f... %F{green}ready.%f"

# Alias for reloading config
alias reloadp10k='source ~/.p10k.zsh && clear && echo "Hacker prompt reloaded."'

# Disable showing UID
POWERLEVEL9K_CONTEXT_TEMPLATE=''


# End of ~/.p10k.zsh
